workflows:
  my-workflow:
    name: Test
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      groups:
        - other
      vars:
        PUBLIC_ENV_VAR: "value here"
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
      cancel_previous_builds: false
    scripts:
      - echo "single line script"
      - name: Build for iOS
        script: flutter build ios --no-codesign
      - name: Creating ipa file
        script: mkdir -p build/ios/iphoneos/Payload
        script: mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload
        script: cd build/ios/iphoneos
        script: zip -r app.ipa Payload
        script: rm -rf Payload
        

    artifacts:
      - build/ios/iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - xkryy.gg@gmail.com
